# Устанавливаем node-js, чтобы скомпилировать конфигурацию nginx.
FROM node:11.8.0 as nginx_conf

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY deploy deploy

ENV NGINX_ENV=production
RUN node deploy/tools/compile-nginx-config.js > nginx.conf

# Устанавливаем python3.5, чтобы выполнить collectstatic.
FROM python:3.5 as static

WORKDIR /app

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY . /app

RUN python3 src/manage.py collectstatic
RUN chown -R www-data:www-data files

FROM nginx:1.15.9

COPY --from=nginx_conf /app/nginx.conf /etc/nginx/nginx.conf
COPY --from=static /app/files/static /srv/bmstu-fun/files/static

CMD ["nginx", "-g", "daemon off;"]
