FROM python:3.5.7

# Отключаем буфер питона для операций вывода (напрмер в консоль),
# чтобы логи сразу выводились, а не кэшировались.
ENV PYTHONBUFFERED 1

RUN mkdir /app
WORKDIR /app
ENV ROOT_DIR /app

COPY --chown=www-data:www-data requirements.txt .
RUN pip install -r requirements.txt

COPY --chown=www-data:www-data . /app/

EXPOSE 8000
CMD ./deploy/start.sh
