# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, unique=True)),
                ('slug', models.CharField(max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('function_name', models.CharField(max_length=100, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolt_sandbox.Section')),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
    ]
